### ISSUE TITLE
Dependency requirements are too strict

### ISSUE THREAD

**Issue by dmitriy-pryan** [karajan1001/aiooss2#86]
Hello,

I'm trying to update `aiohttp` to the most recent version.
However, `aiooss2` prevents me from doing that, because it have `aiohttp` pinned to `==3.8.5`.

I think it would be more convenient for end users of `aiooss2` to be able to update sub-dependencies on their own, instead of asking every time like this: https://github.com/karajan1001/aiooss2/issues/75

If `aiooss2` doesn't use anything too specific from `aiohttp`'s exact version, I suppose pinning only the major version wouldn't break anything.
Do you consider loosening restrictions for `aiohttp` a bit, making it for example `>=3.8.5,<4.0.0`?

**Comment by karajan1001** [comment]
Close it as already been solved in #89.
